import jsPDF from "jspdf";
import { supabase } from "@/integrations/supabase/client";

interface ReportData {
  fileName: string;
  model: string;
  scaleFactor: string;
  originalDimensions: [number, number];
  enhancedDimensions: [number, number];
  metrics: { psnr: number; ssim: number; processing_time: number };
  analysis?: string;
  timestamp?: string;
}

export async function generateEnhancementReport(data: ReportData): Promise<Blob> {
  // 1. Call edge function for AI report text
  const { data: fnData, error } = await supabase.functions.invoke("generate-report", {
    body: {
      metrics: data.metrics,
      originalDimensions: data.originalDimensions,
      enhancedDimensions: data.enhancedDimensions,
      model: data.model,
      scaleFactor: data.scaleFactor,
      fileName: data.fileName,
      analysis: data.analysis,
    },
  });

  const aiReport = error ? "AI report generation unavailable." : (fnData?.report ?? "");

  // 2. Build PDF
  const doc = new jsPDF({ unit: "mm", format: "a4" });
  const W = doc.internal.pageSize.getWidth();
  const margin = 18;
  const contentW = W - margin * 2;
  let y = margin;

  const addText = (text: string, size: number, style: "normal" | "bold" = "normal", color: [number, number, number] = [33, 33, 33]) => {
    doc.setFontSize(size);
    doc.setFont("helvetica", style);
    doc.setTextColor(...color);
  };

  // Header bar
  doc.setFillColor(15, 23, 42); // slate-900
  doc.rect(0, 0, W, 36, "F");
  doc.setFillColor(6, 182, 212); // cyan-500
  doc.rect(0, 36, W, 1.5, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("TerraLens", margin, 16);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Satellite Image Enhancement Report", margin, 24);

  const dateStr = data.timestamp ? new Date(data.timestamp).toLocaleString() : new Date().toLocaleString();
  doc.setFontSize(8);
  doc.text(dateStr, W - margin, 24, { align: "right" });

  y = 46;

  // Section helper
  const section = (title: string) => {
    if (y > 260) { doc.addPage(); y = margin; }
    doc.setFillColor(6, 182, 212);
    doc.rect(margin, y, 3, 6, "F");
    addText(title, 12, "bold", [15, 23, 42]);
    doc.text(title, margin + 6, y + 5);
    y += 12;
  };

  const kvRow = (label: string, value: string) => {
    if (y > 275) { doc.addPage(); y = margin; }
    addText(label, 9, "normal", [100, 116, 139]);
    doc.text(label, margin + 2, y);
    addText(value, 9, "bold", [33, 33, 33]);
    doc.text(value, margin + 60, y);
    y += 6;
  };

  // Enhancement Summary
  section("Enhancement Summary");
  kvRow("File Name", data.fileName);
  kvRow("Model", data.model.toUpperCase());
  kvRow("Scale Factor", `${data.scaleFactor}×`);
  kvRow("Processing Time", `${data.metrics.processing_time.toFixed(1)}s`);
  kvRow("Date", dateStr);
  y += 4;

  // Resolution Details
  section("Resolution Details");
  kvRow("Original", `${data.originalDimensions[0]} × ${data.originalDimensions[1]} px`);
  kvRow("Enhanced", `${data.enhancedDimensions[0]} × ${data.enhancedDimensions[1]} px`);
  kvRow("Pixel Increase", `${((data.enhancedDimensions[0] * data.enhancedDimensions[1]) / (data.originalDimensions[0] * data.originalDimensions[1])).toFixed(1)}×`);
  y += 4;

  // Quality Metrics
  section("Quality Metrics");
  kvRow("PSNR", `${data.metrics.psnr.toFixed(2)} dB`);
  kvRow("SSIM", data.metrics.ssim.toFixed(4));

  // PSNR bar
  const psnrPct = Math.min(data.metrics.psnr / 40, 1);
  doc.setFillColor(226, 232, 240);
  doc.roundedRect(margin + 60, y - 1, 80, 4, 2, 2, "F");
  doc.setFillColor(6, 182, 212);
  doc.roundedRect(margin + 60, y - 1, 80 * psnrPct, 4, 2, 2, "F");
  addText("PSNR", 7, "normal", [100, 116, 139]);
  doc.text("PSNR", margin + 2, y + 2);
  y += 8;

  // SSIM bar
  const ssimPct = Math.min(data.metrics.ssim, 1);
  doc.setFillColor(226, 232, 240);
  doc.roundedRect(margin + 60, y - 1, 80, 4, 2, 2, "F");
  doc.setFillColor(139, 92, 246);
  doc.roundedRect(margin + 60, y - 1, 80 * ssimPct, 4, 2, 2, "F");
  addText("SSIM", 7, "normal", [100, 116, 139]);
  doc.text("SSIM", margin + 2, y + 2);
  y += 12;

  // AI Analysis
  if (aiReport) {
    section("AI Analysis & Detected Features");
    addText("", 9, "normal", [51, 65, 85]);
    const lines = doc.splitTextToSize(aiReport, contentW - 4);
    for (const line of lines) {
      if (y > 275) { doc.addPage(); y = margin; }
      doc.text(line, margin + 2, y);
      y += 4.5;
    }
  }

  // Footer
  const pages = doc.getNumberOfPages();
  for (let i = 1; i <= pages; i++) {
    doc.setPage(i);
    doc.setFillColor(241, 245, 249);
    doc.rect(0, 287, W, 10, "F");
    doc.setFontSize(7);
    doc.setTextColor(148, 163, 184);
    doc.text("Generated by TerraLens · terralens.lovable.app", margin, 293);
    doc.text(`Page ${i} of ${pages}`, W - margin, 293, { align: "right" });
  }

  return doc.output("blob");
}
